server:
  port: 8020
  servlet:
    context-path: /system

spring:
  application:
    name: happyboot-api-sys

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    generator:
  #      write_numbers_as_strings: true

  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
  data:
    mongodb:
      port: 27017
      database: happyboot
      host: 101.132.132.97
  #     username:
  #     password:

  rabbitmq:
    host: 10.10.0.14
    port: 5672
    username: happyboot
    password: happyboot
    virtual-host: /happyboot

  datasource:
    url: jdbc:mysql://101.132.132.97:3306/db_happyboot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: chenxudong0926

#  autoconfigure:
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#  datasource:
#    dynamic:
#      primary: master
#      datasource:
#        master:
#          username: root
#          password: JiaShanLiT0ng$2O17
#          url: jdbc:mysql://192.7.2.103:3306/db_ltit_cloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
#        slave_1:
#          url: jdbc:mysql://localhost:3306/test20200327?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
#          username: root
#          password: root

mybatis-plus:
  configuration:
    # 配置sql打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自定义类型转换器注入扫描
  type-handlers-package: org.happykit.happyboot.handler

token:
  # 是否开启单设备登陆 仅当token交互方式为redis时生效
  sdl: false
  # token过期时间 redis模式有请求自动刷新（分钟）
  tokenExpireTime: 43200
  # 用户选择 保存登录状态/记住我 对应token过期时间（天）
  saveLoginTime: 7
  # 客户端登录失败限制（次）
  loginFailedLimit: 5
  # 客户端登录失败限制恢复时间（分钟）
  loginFailedLimitRecoverTime: 10
  authorization: Authorization
#  bearer: Bearer

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /login2 # 登录接口
    - /sendMsg

ignored:
  urls:
    - /
    - /kaptcha/**
    - /login
    - /demo/**
    - /sys/file/** # 文件相关接口
  #    - /sys/**
  #    - /swagger-resources
  #    - /swagger-resources/**
  #    - /configuration/ui
  #    - /configuration/security
  #    - /swagger-ui.html
  #    - /webjars/**
  #    - /druid/**
  client-id-urls:
    - /
    - /sys/file/view/**
