server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    generator:
  #      write_numbers_as_strings: true

  redis:
    database: 3
    host: redis
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms

  data:
    mongodb:
      port: 27017
      database: logs
      host: mongodb
  #     username:
  #     password:

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: chenxudong0926
  #    virtual-host: /happyboot

  datasource:
    url: jdbc:mysql://mysql5.7:3306/db_happyboot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: chenxudong0926

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  # 默认为true，token将存入redis，并具有单点登录功能 设为false使用JWT交互
  redis: true
  # 是否开启单设备登陆 仅当token交互方式为redis时生效
  sdl: false
  # token过期时间 redis模式有请求自动刷新（分钟）
  tokenExpireTime: 1440
  # 用户选择 保存登录状态/记住我 对应token过期时间（天）
  saveLoginTime: 7
  # 客户端登录失败限制（次）
  loginFailedLimit: 5
  # 客户端登录失败限制恢复时间（分钟）
  loginFailedLimitRecoverTime: 10
  secret: 123456
  authorization: Authorization
  #  bearer: Bearer

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  # 图片验证码验证
  image:
    - /login # 登录接口

ignored:
  urls:
    - /
    - /kaptcha/**
    - /login
    - /sys/file/**        # 文件相关接口
    - /swagger-resources
    - /swagger-resources/**
    - /configuration/ui
    - /configuration/security
    - /swagger-ui.html
    - /webjars/**
    - /druid/**
  client-id-urls:
    - /
    - /sys/file/view/**
